import React from "react";

const Privacy: React.FC = () => {
  return (
    <div className="min-h-screen bg-background-dark px-4 pb-20 pt-32 sm:px-6">
      <div className="ui-container max-w-4xl">
        <header className="border-b border-white/10 pb-9">
          <p className="ui-eyebrow">
            Privacy Notice
          </p>
          <h1 className="ui-page-title mt-3 text-white">
            Your Data, <span className="italic">Clearly Explained</span>
          </h1>
          <p className="mt-4 text-sm text-gray-500">
            Last Updated: July 13, 2026
          </p>
        </header>

        <div className="mt-10 space-y-10 text-[0.96rem] leading-8 text-gray-400">
          <PolicySection title="1. Who This Notice Covers">
            <p>
              This notice explains how Moore Hotels &amp; Suites handles personal data when you
              browse this website, create an account, make or manage a reservation, contact us,
              pay for a stay, or interact with the hotel. It should be read together with the
              terms attached to your reservation.
            </p>
          </PolicySection>

          <PolicySection title="2. Information We Collect">
            <p>Depending on how you use our services, we may collect:</p>
            <ul className="list-disc pl-6 space-y-2 marker:text-primary">
              <li>Your name, email address, telephone number, and account details.</li>
              <li>Reservation dates, room selection, booking reference, status, and requests.</li>
              <li>Payment status and transaction references supplied by our payment provider.</li>
              <li>Messages, cancellation reasons, support requests, and stay history.</li>
              <li>
                Basic technical and security records, such as request times, device or browser
                information, and service logs where generated by our hosting or security systems.
              </li>
            </ul>
            <p>
              Online card payments are handled by the payment provider. This website is not
              designed to receive or store your full card number or card security code.
            </p>
          </PolicySection>

          <PolicySection title="3. Why We Use It">
            <ul className="list-disc pl-6 space-y-2 marker:text-primary">
              <li>To search availability, create reservations, and provide hotel services.</li>
              <li>To process or verify payments, cancellations, and refunds.</li>
              <li>To authenticate accounts and protect guests, staff, and our systems.</li>
              <li>To send operational messages about accounts, payments, and reservations.</li>
              <li>To meet legal, accounting, safety, fraud-prevention, and dispute obligations.</li>
              <li>
                To send marketing only where a lawful basis applies; the current website does not
                complete an online newsletter subscription.
              </li>
            </ul>
          </PolicySection>

          <PolicySection title="4. Service Providers and Sharing">
            <p>
              We may share only the data needed with providers that support payment processing,
              email delivery, cloud hosting, image delivery, security, and other hotel operations.
              We may also disclose data where required by law, to protect a person or the hotel,
              or as part of a properly governed business transaction. We do not sell guest data.
            </p>
          </PolicySection>

          <PolicySection title="5. Storage, Retention, and Security">
            <p>
              We retain information only for as long as needed for reservations, guest service,
              accounting, legal claims, security, and other documented business requirements.
              Retention periods can differ by record type. We use measures such as HTTPS,
              authenticated staff access, and access controls, but no online service can promise
              absolute security. Please do not send card security codes or passwords by email.
            </p>
          </PolicySection>

          <PolicySection title="6. Browser Storage and External Content">
            <p>
              The website uses tab-scoped browser storage to keep you signed in and to securely
              reconnect you with a booking after payment. That information is removed when the tab
              session ends or you sign out. Pages may load fonts, images, video, or payment pages
              from third-party services, which may receive ordinary connection information under
              their own notices. We do not currently use advertising cookies on this website.
            </p>
          </PolicySection>

          <PolicySection title="7. Your Rights">
            <p>
              Subject to applicable law and identity verification, you may ask whether we process
              your data and request access, correction, deletion, restriction, portability, or an
              objection to certain processing. You may also complain to the Nigeria Data
              Protection Commission. The Commission publishes further information about data
              subject rights under the Nigeria Data Protection Act 2023 on its official website.
            </p>
            <a
              href="https://www.ndpc.gov.ng/"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block text-primary hover:text-white transition-colors"
            >
              Nigeria Data Protection Commission
            </a>
          </PolicySection>

          <PolicySection title="8. Contact Us">
            <p>
              For privacy questions or requests, contact{" "}
              <a
                className="text-primary italic hover:text-white"
                href="mailto:info@moorehotelandsuites.com"
              >
                info@moorehotelandsuites.com
              </a>
              , call +234 803 377 4544, or write to Moore Hotels &amp; Suites, Harmony
              Estate, Along Sagamu–Ikenne Road, Beside NYSC Camp, Sagamu, Ogun State,
              Nigeria.
            </p>
          </PolicySection>
        </div>

        <footer className="mt-12 flex justify-center border-t border-white/10 pt-8">
          <button
            onClick={() => window.print()}
            className="ui-button ui-button-secondary"
          >
            <span className="material-symbols-outlined" aria-hidden="true">print</span> Print notice
          </button>
        </footer>
      </div>
    </div>
  );
};

const PolicySection = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => (
  <section>
    <h2 className="ui-card-title mb-4 italic text-white">{title}</h2>
    {children}
  </section>
);

export default Privacy;
